variables:
    GIT_STRATEGY: clone

stages:
    - test

before_script:

#ClangFormatCheck:
#  stage: test
#  image: bce7edfda510
#  script:
#  - ./.github/automation/clang-format.sh

fcc_w/_SSL2:
  stage: test
  image: bce7edfda510
  script:
#    - pwd
#    - ls
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - source .github/automation/env/setenv-fcc
    - export ONEDNN_ROOT_DIR=`pwd`
    - .github/automation/build.sh --threading omp --mode Release --source-dir $(pwd) --build-dir $(pwd)/build --cmake-opt -DWITH_BLAS=ssl2
    - .github/automation/test.sh --test-kind gtest --build-dir $(pwd)/build --report-dir $(pwd)/report
